### ISSUE TITLE
Code to original paper?

### ISSUE THREAD

**Issue by BabaYara** [yolsever/ML-in-equity-prediction#1]
In your code (stock_price.ipynb), you have a comment that reads, "## they never merge it".  It got me wondering if the code to the paper "Empirical Asset Pricing via Machine Learning", that I believe you are working off, was ever published by the authors?

**Comment by yolsever** [comment]
Yes the original paper got published. I am sorry for my late reply. Let me know if you have other questions. The link is: https://dachxiu.chicagobooth.edu/download/ML.pdf

**Comment by XinL97** [comment]
Is there any way I can get the data?

**Comment by yolsever** [comment]
@XinL97 I am sorry for my extremely late reply but the data can be downloaded using the SAS code I shared. You need an account on WRDS though.

@BabaYara I realized that I did not answer your question. No, the code was not published, however, you can access the paper using the link I shared. I wrote this code myself, trying my best to replicate what the authors were saying on the paper.
